// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: riva_audio.proto

// Audio encodings shared by the NVIDIA Riva speech services. It mirrors the
// upstream riva_audio.proto: the package name and every enum value match, so
// the wire format is compatible with any Riva/NIM server. Regenerate with:
//
//	go generate ./provider/nvidia/internal/rivapb

package rivapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AudioEncoding of the raw audio bytes in the enclosing message.
type AudioEncoding int32

const (
	AudioEncoding_ENCODING_UNSPECIFIED AudioEncoding = 0
	AudioEncoding_LINEAR_PCM           AudioEncoding = 1
	AudioEncoding_FLAC                 AudioEncoding = 2
	AudioEncoding_MULAW                AudioEncoding = 3
	AudioEncoding_OGGOPUS              AudioEncoding = 4
	AudioEncoding_ALAW                 AudioEncoding = 20
)

// Enum value maps for AudioEncoding.
var (
	AudioEncoding_name = map[int32]string{
		0:  "ENCODING_UNSPECIFIED",
		1:  "LINEAR_PCM",
		2:  "FLAC",
		3:  "MULAW",
		4:  "OGGOPUS",
		20: "ALAW",
	}
	AudioEncoding_value = map[string]int32{
		"ENCODING_UNSPECIFIED": 0,
		"LINEAR_PCM":           1,
		"FLAC":                 2,
		"MULAW":                3,
		"OGGOPUS":              4,
		"ALAW":                 20,
	}
)

func (x AudioEncoding) Enum() *AudioEncoding {
	p := new(AudioEncoding)
	*p = x
	return p
}

func (x AudioEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_riva_audio_proto_enumTypes[0].Descriptor()
}

func (AudioEncoding) Type() protoreflect.EnumType {
	return &file_riva_audio_proto_enumTypes[0]
}

func (x AudioEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioEncoding.Descriptor instead.
func (AudioEncoding) EnumDescriptor() ([]byte, []int) {
	return file_riva_audio_proto_rawDescGZIP(), []int{0}
}

var File_riva_audio_proto protoreflect.FileDescriptor

const file_riva_audio_proto_rawDesc = "" +
	"\n" +
	"\x10riva_audio.proto\x12\vnvidia.riva*e\n" +
	"\rAudioEncoding\x12\x18\n" +
	"\x14ENCODING_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"LINEAR_PCM\x10\x01\x12\b\n" +
	"\x04FLAC\x10\x02\x12\t\n" +
	"\x05MULAW\x10\x03\x12\v\n" +
	"\aOGGOPUS\x10\x04\x12\b\n" +
	"\x04ALAW\x10\x14BAZ?github.com/gojargo/jargo/provider/nvidia/internal/rivapb;rivapbb\x06proto3"

var (
	file_riva_audio_proto_rawDescOnce sync.Once
	file_riva_audio_proto_rawDescData []byte
)

func file_riva_audio_proto_rawDescGZIP() []byte {
	file_riva_audio_proto_rawDescOnce.Do(func() {
		file_riva_audio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_riva_audio_proto_rawDesc), len(file_riva_audio_proto_rawDesc)))
	})
	return file_riva_audio_proto_rawDescData
}

var file_riva_audio_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_riva_audio_proto_goTypes = []any{
	(AudioEncoding)(0), // 0: nvidia.riva.AudioEncoding
}
var file_riva_audio_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_riva_audio_proto_init() }
func file_riva_audio_proto_init() {
	if File_riva_audio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_riva_audio_proto_rawDesc), len(file_riva_audio_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_riva_audio_proto_goTypes,
		DependencyIndexes: file_riva_audio_proto_depIdxs,
		EnumInfos:         file_riva_audio_proto_enumTypes,
	}.Build()
	File_riva_audio_proto = out.File
	file_riva_audio_proto_goTypes = nil
	file_riva_audio_proto_depIdxs = nil
}
