// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: riva_tts.proto

// Minimal subset of the NVIDIA Riva speech-synthesis gRPC contract, limited to
// the messages the streaming TTS client uses. Field numbers, the package name,
// and the service/method names match the upstream Riva schema exactly so the
// wire format and the gRPC method path are compatible with any Riva/NIM server
// (hosted NVCF or a locally deployed model such as magpie). Regenerate with:
//
//	go generate ./provider/nvidia/internal/rivapb

package rivapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RivaSpeechSynthesis_SynthesizeOnline_FullMethodName = "/nvidia.riva.tts.RivaSpeechSynthesis/SynthesizeOnline"
)

// RivaSpeechSynthesisClient is the client API for RivaSpeechSynthesis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RivaSpeechSynthesis is the Riva TTS service. Only the streaming RPC is
// declared here; the batch Synthesize and the config RPC are omitted.
type RivaSpeechSynthesisClient interface {
	// SynthesizeOnline streams synthesis requests to the server and receives the
	// audio back as it is generated. The stream is bidirectional: sending several
	// requests on one call is what lets a model stitch across sentences.
	SynthesizeOnline(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SynthesizeSpeechRequest, SynthesizeSpeechResponse], error)
}

type rivaSpeechSynthesisClient struct {
	cc grpc.ClientConnInterface
}

func NewRivaSpeechSynthesisClient(cc grpc.ClientConnInterface) RivaSpeechSynthesisClient {
	return &rivaSpeechSynthesisClient{cc}
}

func (c *rivaSpeechSynthesisClient) SynthesizeOnline(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SynthesizeSpeechRequest, SynthesizeSpeechResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RivaSpeechSynthesis_ServiceDesc.Streams[0], RivaSpeechSynthesis_SynthesizeOnline_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SynthesizeSpeechRequest, SynthesizeSpeechResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RivaSpeechSynthesis_SynthesizeOnlineClient = grpc.BidiStreamingClient[SynthesizeSpeechRequest, SynthesizeSpeechResponse]

// RivaSpeechSynthesisServer is the server API for RivaSpeechSynthesis service.
// All implementations must embed UnimplementedRivaSpeechSynthesisServer
// for forward compatibility.
//
// RivaSpeechSynthesis is the Riva TTS service. Only the streaming RPC is
// declared here; the batch Synthesize and the config RPC are omitted.
type RivaSpeechSynthesisServer interface {
	// SynthesizeOnline streams synthesis requests to the server and receives the
	// audio back as it is generated. The stream is bidirectional: sending several
	// requests on one call is what lets a model stitch across sentences.
	SynthesizeOnline(grpc.BidiStreamingServer[SynthesizeSpeechRequest, SynthesizeSpeechResponse]) error
	mustEmbedUnimplementedRivaSpeechSynthesisServer()
}

// UnimplementedRivaSpeechSynthesisServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRivaSpeechSynthesisServer struct{}

func (UnimplementedRivaSpeechSynthesisServer) SynthesizeOnline(grpc.BidiStreamingServer[SynthesizeSpeechRequest, SynthesizeSpeechResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SynthesizeOnline not implemented")
}
func (UnimplementedRivaSpeechSynthesisServer) mustEmbedUnimplementedRivaSpeechSynthesisServer() {}
func (UnimplementedRivaSpeechSynthesisServer) testEmbeddedByValue()                             {}

// UnsafeRivaSpeechSynthesisServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RivaSpeechSynthesisServer will
// result in compilation errors.
type UnsafeRivaSpeechSynthesisServer interface {
	mustEmbedUnimplementedRivaSpeechSynthesisServer()
}

func RegisterRivaSpeechSynthesisServer(s grpc.ServiceRegistrar, srv RivaSpeechSynthesisServer) {
	// If the following call pancis, it indicates UnimplementedRivaSpeechSynthesisServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RivaSpeechSynthesis_ServiceDesc, srv)
}

func _RivaSpeechSynthesis_SynthesizeOnline_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RivaSpeechSynthesisServer).SynthesizeOnline(&grpc.GenericServerStream[SynthesizeSpeechRequest, SynthesizeSpeechResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RivaSpeechSynthesis_SynthesizeOnlineServer = grpc.BidiStreamingServer[SynthesizeSpeechRequest, SynthesizeSpeechResponse]

// RivaSpeechSynthesis_ServiceDesc is the grpc.ServiceDesc for RivaSpeechSynthesis service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RivaSpeechSynthesis_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nvidia.riva.tts.RivaSpeechSynthesis",
	HandlerType: (*RivaSpeechSynthesisServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SynthesizeOnline",
			Handler:       _RivaSpeechSynthesis_SynthesizeOnline_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "riva_tts.proto",
}
