// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: riva.proto

// Minimal subset of the NVIDIA Riva speech-recognition gRPC contract, limited to
// the messages the streaming ASR client uses. Field numbers, the package name,
// and the service/method names match the upstream Riva schema exactly so the
// wire format and the gRPC method path are compatible with any Riva/NIM server
// (hosted NVCF or a locally deployed model such as parakeet). Regenerate with:
//
//	go generate ./provider/nvidia/internal/rivapb

package rivapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AudioEncoding of the raw audio bytes sent to the server.
type AudioEncoding int32

const (
	AudioEncoding_ENCODING_UNSPECIFIED AudioEncoding = 0
	AudioEncoding_LINEAR_PCM           AudioEncoding = 1
	AudioEncoding_FLAC                 AudioEncoding = 2
	AudioEncoding_MULAW                AudioEncoding = 3
	AudioEncoding_OGGOPUS              AudioEncoding = 4
	AudioEncoding_ALAW                 AudioEncoding = 20
)

// Enum value maps for AudioEncoding.
var (
	AudioEncoding_name = map[int32]string{
		0:  "ENCODING_UNSPECIFIED",
		1:  "LINEAR_PCM",
		2:  "FLAC",
		3:  "MULAW",
		4:  "OGGOPUS",
		20: "ALAW",
	}
	AudioEncoding_value = map[string]int32{
		"ENCODING_UNSPECIFIED": 0,
		"LINEAR_PCM":           1,
		"FLAC":                 2,
		"MULAW":                3,
		"OGGOPUS":              4,
		"ALAW":                 20,
	}
)

func (x AudioEncoding) Enum() *AudioEncoding {
	p := new(AudioEncoding)
	*p = x
	return p
}

func (x AudioEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_riva_proto_enumTypes[0].Descriptor()
}

func (AudioEncoding) Type() protoreflect.EnumType {
	return &file_riva_proto_enumTypes[0]
}

func (x AudioEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioEncoding.Descriptor instead.
func (AudioEncoding) EnumDescriptor() ([]byte, []int) {
	return file_riva_proto_rawDescGZIP(), []int{0}
}

// StreamingRecognizeRequest is either the opening config or a chunk of audio.
type StreamingRecognizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to StreamingRequest:
	//
	//	*StreamingRecognizeRequest_StreamingConfig
	//	*StreamingRecognizeRequest_AudioContent
	StreamingRequest isStreamingRecognizeRequest_StreamingRequest `protobuf_oneof:"streaming_request"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamingRecognizeRequest) Reset() {
	*x = StreamingRecognizeRequest{}
	mi := &file_riva_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingRecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingRecognizeRequest) ProtoMessage() {}

func (x *StreamingRecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_riva_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingRecognizeRequest.ProtoReflect.Descriptor instead.
func (*StreamingRecognizeRequest) Descriptor() ([]byte, []int) {
	return file_riva_proto_rawDescGZIP(), []int{0}
}

func (x *StreamingRecognizeRequest) GetStreamingRequest() isStreamingRecognizeRequest_StreamingRequest {
	if x != nil {
		return x.StreamingRequest
	}
	return nil
}

func (x *StreamingRecognizeRequest) GetStreamingConfig() *StreamingRecognitionConfig {
	if x != nil {
		if x, ok := x.StreamingRequest.(*StreamingRecognizeRequest_StreamingConfig); ok {
			return x.StreamingConfig
		}
	}
	return nil
}

func (x *StreamingRecognizeRequest) GetAudioContent() []byte {
	if x != nil {
		if x, ok := x.StreamingRequest.(*StreamingRecognizeRequest_AudioContent); ok {
			return x.AudioContent
		}
	}
	return nil
}

type isStreamingRecognizeRequest_StreamingRequest interface {
	isStreamingRecognizeRequest_StreamingRequest()
}

type StreamingRecognizeRequest_StreamingConfig struct {
	StreamingConfig *StreamingRecognitionConfig `protobuf:"bytes,1,opt,name=streaming_config,json=streamingConfig,proto3,oneof"`
}

type StreamingRecognizeRequest_AudioContent struct {
	AudioContent []byte `protobuf:"bytes,2,opt,name=audio_content,json=audioContent,proto3,oneof"`
}

func (*StreamingRecognizeRequest_StreamingConfig) isStreamingRecognizeRequest_StreamingRequest() {}

func (*StreamingRecognizeRequest_AudioContent) isStreamingRecognizeRequest_StreamingRequest() {}

// StreamingRecognitionConfig configures a streaming session.
type StreamingRecognitionConfig struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Config *RecognitionConfig     `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// interim_results asks the server to emit tentative (is_final=false) results.
	InterimResults bool `protobuf:"varint,2,opt,name=interim_results,json=interimResults,proto3" json:"interim_results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamingRecognitionConfig) Reset() {
	*x = StreamingRecognitionConfig{}
	mi := &file_riva_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingRecognitionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingRecognitionConfig) ProtoMessage() {}

func (x *StreamingRecognitionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_riva_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingRecognitionConfig.ProtoReflect.Descriptor instead.
func (*StreamingRecognitionConfig) Descriptor() ([]byte, []int) {
	return file_riva_proto_rawDescGZIP(), []int{1}
}

func (x *StreamingRecognitionConfig) GetConfig() *RecognitionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *StreamingRecognitionConfig) GetInterimResults() bool {
	if x != nil {
		return x.InterimResults
	}
	return false
}

// RecognitionConfig tells the recognizer how to process the audio.
type RecognitionConfig struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Encoding                   AudioEncoding          `protobuf:"varint,1,opt,name=encoding,proto3,enum=nvidia.riva.asr.AudioEncoding" json:"encoding,omitempty"`
	SampleRateHertz            int32                  `protobuf:"varint,2,opt,name=sample_rate_hertz,json=sampleRateHertz,proto3" json:"sample_rate_hertz,omitempty"`
	LanguageCode               string                 `protobuf:"bytes,3,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	MaxAlternatives            int32                  `protobuf:"varint,4,opt,name=max_alternatives,json=maxAlternatives,proto3" json:"max_alternatives,omitempty"`
	ProfanityFilter            bool                   `protobuf:"varint,5,opt,name=profanity_filter,json=profanityFilter,proto3" json:"profanity_filter,omitempty"`
	AudioChannelCount          int32                  `protobuf:"varint,7,opt,name=audio_channel_count,json=audioChannelCount,proto3" json:"audio_channel_count,omitempty"`
	EnableWordTimeOffsets      bool                   `protobuf:"varint,8,opt,name=enable_word_time_offsets,json=enableWordTimeOffsets,proto3" json:"enable_word_time_offsets,omitempty"`
	EnableAutomaticPunctuation bool                   `protobuf:"varint,11,opt,name=enable_automatic_punctuation,json=enableAutomaticPunctuation,proto3" json:"enable_automatic_punctuation,omitempty"`
	// model selects the served model by name; empty lets the server choose.
	Model               string             `protobuf:"bytes,13,opt,name=model,proto3" json:"model,omitempty"`
	VerbatimTranscripts bool               `protobuf:"varint,14,opt,name=verbatim_transcripts,json=verbatimTranscripts,proto3" json:"verbatim_transcripts,omitempty"`
	CustomConfiguration map[string]string  `protobuf:"bytes,24,rep,name=custom_configuration,json=customConfiguration,proto3" json:"custom_configuration,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EndpointingConfig   *EndpointingConfig `protobuf:"bytes,25,opt,name=endpointing_config,json=endpointingConfig,proto3,oneof" json:"endpointing_config,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RecognitionConfig) Reset() {
	*x = RecognitionConfig{}
	mi := &file_riva_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognitionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognitionConfig) ProtoMessage() {}

func (x *RecognitionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_riva_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognitionConfig.ProtoReflect.Descriptor instead.
func (*RecognitionConfig) Descriptor() ([]byte, []int) {
	return file_riva_proto_rawDescGZIP(), []int{2}
}

func (x *RecognitionConfig) GetEncoding() AudioEncoding {
	if x != nil {
		return x.Encoding
	}
	return AudioEncoding_ENCODING_UNSPECIFIED
}

func (x *RecognitionConfig) GetSampleRateHertz() int32 {
	if x != nil {
		return x.SampleRateHertz
	}
	return 0
}

func (x *RecognitionConfig) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *RecognitionConfig) GetMaxAlternatives() int32 {
	if x != nil {
		return x.MaxAlternatives
	}
	return 0
}

func (x *RecognitionConfig) GetProfanityFilter() bool {
	if x != nil {
		return x.ProfanityFilter
	}
	return false
}

func (x *RecognitionConfig) GetAudioChannelCount() int32 {
	if x != nil {
		return x.AudioChannelCount
	}
	return 0
}

func (x *RecognitionConfig) GetEnableWordTimeOffsets() bool {
	if x != nil {
		return x.EnableWordTimeOffsets
	}
	return false
}

func (x *RecognitionConfig) GetEnableAutomaticPunctuation() bool {
	if x != nil {
		return x.EnableAutomaticPunctuation
	}
	return false
}

func (x *RecognitionConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RecognitionConfig) GetVerbatimTranscripts() bool {
	if x != nil {
		return x.VerbatimTranscripts
	}
	return false
}

func (x *RecognitionConfig) GetCustomConfiguration() map[string]string {
	if x != nil {
		return x.CustomConfiguration
	}
	return nil
}

func (x *RecognitionConfig) GetEndpointingConfig() *EndpointingConfig {
	if x != nil {
		return x.EndpointingConfig
	}
	return nil
}

// EndpointingConfig tunes the server-side start/end-of-utterance detector. Every
// field is optional; unset fields keep the server's built-in defaults.
type EndpointingConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StartHistory     *int32                 `protobuf:"varint,1,opt,name=start_history,json=startHistory,proto3,oneof" json:"start_history,omitempty"`
	StartThreshold   *float32               `protobuf:"fixed32,2,opt,name=start_threshold,json=startThreshold,proto3,oneof" json:"start_threshold,omitempty"`
	StopHistory      *int32                 `protobuf:"varint,3,opt,name=stop_history,json=stopHistory,proto3,oneof" json:"stop_history,omitempty"`
	StopThreshold    *float32               `protobuf:"fixed32,4,opt,name=stop_threshold,json=stopThreshold,proto3,oneof" json:"stop_threshold,omitempty"`
	StopHistoryEou   *int32                 `protobuf:"varint,5,opt,name=stop_history_eou,json=stopHistoryEou,proto3,oneof" json:"stop_history_eou,omitempty"`
	StopThresholdEou *float32               `protobuf:"fixed32,6,opt,name=stop_threshold_eou,json=stopThresholdEou,proto3,oneof" json:"stop_threshold_eou,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EndpointingConfig) Reset() {
	*x = EndpointingConfig{}
	mi := &file_riva_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointingConfig) ProtoMessage() {}

func (x *EndpointingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_riva_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointingConfig.ProtoReflect.Descriptor instead.
func (*EndpointingConfig) Descriptor() ([]byte, []int) {
	return file_riva_proto_rawDescGZIP(), []int{3}
}

func (x *EndpointingConfig) GetStartHistory() int32 {
	if x != nil && x.StartHistory != nil {
		return *x.StartHistory
	}
	return 0
}

func (x *EndpointingConfig) GetStartThreshold() float32 {
	if x != nil && x.StartThreshold != nil {
		return *x.StartThreshold
	}
	return 0
}

func (x *EndpointingConfig) GetStopHistory() int32 {
	if x != nil && x.StopHistory != nil {
		return *x.StopHistory
	}
	return 0
}

func (x *EndpointingConfig) GetStopThreshold() float32 {
	if x != nil && x.StopThreshold != nil {
		return *x.StopThreshold
	}
	return 0
}

func (x *EndpointingConfig) GetStopHistoryEou() int32 {
	if x != nil && x.StopHistoryEou != nil {
		return *x.StopHistoryEou
	}
	return 0
}

func (x *EndpointingConfig) GetStopThresholdEou() float32 {
	if x != nil && x.StopThresholdEou != nil {
		return *x.StopThresholdEou
	}
	return 0
}

// StreamingRecognizeResponse carries the latest transcript(s).
type StreamingRecognizeResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Results       []*StreamingRecognitionResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingRecognizeResponse) Reset() {
	*x = StreamingRecognizeResponse{}
	mi := &file_riva_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingRecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingRecognizeResponse) ProtoMessage() {}

func (x *StreamingRecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_riva_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingRecognizeResponse.ProtoReflect.Descriptor instead.
func (*StreamingRecognizeResponse) Descriptor() ([]byte, []int) {
	return file_riva_proto_rawDescGZIP(), []int{4}
}

func (x *StreamingRecognizeResponse) GetResults() []*StreamingRecognitionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// StreamingRecognitionResult is one transcript hypothesis set for a portion of
// audio. is_final marks the final result for that portion (end of utterance
// when server-side endpointing is enabled).
type StreamingRecognitionResult struct {
	state          protoimpl.MessageState          `protogen:"open.v1"`
	Alternatives   []*SpeechRecognitionAlternative `protobuf:"bytes,1,rep,name=alternatives,proto3" json:"alternatives,omitempty"`
	IsFinal        bool                            `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	Stability      float32                         `protobuf:"fixed32,3,opt,name=stability,proto3" json:"stability,omitempty"`
	ChannelTag     int32                           `protobuf:"varint,5,opt,name=channel_tag,json=channelTag,proto3" json:"channel_tag,omitempty"`
	AudioProcessed float32                         `protobuf:"fixed32,6,opt,name=audio_processed,json=audioProcessed,proto3" json:"audio_processed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamingRecognitionResult) Reset() {
	*x = StreamingRecognitionResult{}
	mi := &file_riva_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingRecognitionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingRecognitionResult) ProtoMessage() {}

func (x *StreamingRecognitionResult) ProtoReflect() protoreflect.Message {
	mi := &file_riva_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingRecognitionResult.ProtoReflect.Descriptor instead.
func (*StreamingRecognitionResult) Descriptor() ([]byte, []int) {
	return file_riva_proto_rawDescGZIP(), []int{5}
}

func (x *StreamingRecognitionResult) GetAlternatives() []*SpeechRecognitionAlternative {
	if x != nil {
		return x.Alternatives
	}
	return nil
}

func (x *StreamingRecognitionResult) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *StreamingRecognitionResult) GetStability() float32 {
	if x != nil {
		return x.Stability
	}
	return 0
}

func (x *StreamingRecognitionResult) GetChannelTag() int32 {
	if x != nil {
		return x.ChannelTag
	}
	return 0
}

func (x *StreamingRecognitionResult) GetAudioProcessed() float32 {
	if x != nil {
		return x.AudioProcessed
	}
	return 0
}

// SpeechRecognitionAlternative is a single transcript hypothesis.
type SpeechRecognitionAlternative struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transcript    string                 `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	LanguageCode  []string               `protobuf:"bytes,4,rep,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeechRecognitionAlternative) Reset() {
	*x = SpeechRecognitionAlternative{}
	mi := &file_riva_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeechRecognitionAlternative) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeechRecognitionAlternative) ProtoMessage() {}

func (x *SpeechRecognitionAlternative) ProtoReflect() protoreflect.Message {
	mi := &file_riva_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeechRecognitionAlternative.ProtoReflect.Descriptor instead.
func (*SpeechRecognitionAlternative) Descriptor() ([]byte, []int) {
	return file_riva_proto_rawDescGZIP(), []int{6}
}

func (x *SpeechRecognitionAlternative) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *SpeechRecognitionAlternative) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SpeechRecognitionAlternative) GetLanguageCode() []string {
	if x != nil {
		return x.LanguageCode
	}
	return nil
}

var File_riva_proto protoreflect.FileDescriptor

const file_riva_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"riva.proto\x12\x0fnvidia.riva.asr\"\xb1\x01\n" +
	"\x19StreamingRecognizeRequest\x12X\n" +
	"\x10streaming_config\x18\x01 \x01(\v2+.nvidia.riva.asr.StreamingRecognitionConfigH\x00R\x0fstreamingConfig\x12%\n" +
	"\raudio_content\x18\x02 \x01(\fH\x00R\faudioContentB\x13\n" +
	"\x11streaming_request\"\x81\x01\n" +
	"\x1aStreamingRecognitionConfig\x12:\n" +
	"\x06config\x18\x01 \x01(\v2\".nvidia.riva.asr.RecognitionConfigR\x06config\x12'\n" +
	"\x0finterim_results\x18\x02 \x01(\bR\x0einterimResults\"\x91\x06\n" +
	"\x11RecognitionConfig\x12:\n" +
	"\bencoding\x18\x01 \x01(\x0e2\x1e.nvidia.riva.asr.AudioEncodingR\bencoding\x12*\n" +
	"\x11sample_rate_hertz\x18\x02 \x01(\x05R\x0fsampleRateHertz\x12#\n" +
	"\rlanguage_code\x18\x03 \x01(\tR\flanguageCode\x12)\n" +
	"\x10max_alternatives\x18\x04 \x01(\x05R\x0fmaxAlternatives\x12)\n" +
	"\x10profanity_filter\x18\x05 \x01(\bR\x0fprofanityFilter\x12.\n" +
	"\x13audio_channel_count\x18\a \x01(\x05R\x11audioChannelCount\x127\n" +
	"\x18enable_word_time_offsets\x18\b \x01(\bR\x15enableWordTimeOffsets\x12@\n" +
	"\x1cenable_automatic_punctuation\x18\v \x01(\bR\x1aenableAutomaticPunctuation\x12\x14\n" +
	"\x05model\x18\r \x01(\tR\x05model\x121\n" +
	"\x14verbatim_transcripts\x18\x0e \x01(\bR\x13verbatimTranscripts\x12n\n" +
	"\x14custom_configuration\x18\x18 \x03(\v2;.nvidia.riva.asr.RecognitionConfig.CustomConfigurationEntryR\x13customConfiguration\x12V\n" +
	"\x12endpointing_config\x18\x19 \x01(\v2\".nvidia.riva.asr.EndpointingConfigH\x00R\x11endpointingConfig\x88\x01\x01\x1aF\n" +
	"\x18CustomConfigurationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x15\n" +
	"\x13_endpointing_config\"\x97\x03\n" +
	"\x11EndpointingConfig\x12(\n" +
	"\rstart_history\x18\x01 \x01(\x05H\x00R\fstartHistory\x88\x01\x01\x12,\n" +
	"\x0fstart_threshold\x18\x02 \x01(\x02H\x01R\x0estartThreshold\x88\x01\x01\x12&\n" +
	"\fstop_history\x18\x03 \x01(\x05H\x02R\vstopHistory\x88\x01\x01\x12*\n" +
	"\x0estop_threshold\x18\x04 \x01(\x02H\x03R\rstopThreshold\x88\x01\x01\x12-\n" +
	"\x10stop_history_eou\x18\x05 \x01(\x05H\x04R\x0estopHistoryEou\x88\x01\x01\x121\n" +
	"\x12stop_threshold_eou\x18\x06 \x01(\x02H\x05R\x10stopThresholdEou\x88\x01\x01B\x10\n" +
	"\x0e_start_historyB\x12\n" +
	"\x10_start_thresholdB\x0f\n" +
	"\r_stop_historyB\x11\n" +
	"\x0f_stop_thresholdB\x13\n" +
	"\x11_stop_history_eouB\x15\n" +
	"\x13_stop_threshold_eou\"c\n" +
	"\x1aStreamingRecognizeResponse\x12E\n" +
	"\aresults\x18\x01 \x03(\v2+.nvidia.riva.asr.StreamingRecognitionResultR\aresults\"\xf2\x01\n" +
	"\x1aStreamingRecognitionResult\x12Q\n" +
	"\falternatives\x18\x01 \x03(\v2-.nvidia.riva.asr.SpeechRecognitionAlternativeR\falternatives\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x12\x1c\n" +
	"\tstability\x18\x03 \x01(\x02R\tstability\x12\x1f\n" +
	"\vchannel_tag\x18\x05 \x01(\x05R\n" +
	"channelTag\x12'\n" +
	"\x0faudio_processed\x18\x06 \x01(\x02R\x0eaudioProcessed\"\x83\x01\n" +
	"\x1cSpeechRecognitionAlternative\x12\x1e\n" +
	"\n" +
	"transcript\x18\x01 \x01(\tR\n" +
	"transcript\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12#\n" +
	"\rlanguage_code\x18\x04 \x03(\tR\flanguageCode*e\n" +
	"\rAudioEncoding\x12\x18\n" +
	"\x14ENCODING_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"LINEAR_PCM\x10\x01\x12\b\n" +
	"\x04FLAC\x10\x02\x12\t\n" +
	"\x05MULAW\x10\x03\x12\v\n" +
	"\aOGGOPUS\x10\x04\x12\b\n" +
	"\x04ALAW\x10\x142\x8c\x01\n" +
	"\x15RivaSpeechRecognition\x12s\n" +
	"\x12StreamingRecognize\x12*.nvidia.riva.asr.StreamingRecognizeRequest\x1a+.nvidia.riva.asr.StreamingRecognizeResponse\"\x00(\x010\x01BAZ?github.com/gojargo/jargo/provider/nvidia/internal/rivapb;rivapbb\x06proto3"

var (
	file_riva_proto_rawDescOnce sync.Once
	file_riva_proto_rawDescData []byte
)

func file_riva_proto_rawDescGZIP() []byte {
	file_riva_proto_rawDescOnce.Do(func() {
		file_riva_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_riva_proto_rawDesc), len(file_riva_proto_rawDesc)))
	})
	return file_riva_proto_rawDescData
}

var file_riva_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_riva_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_riva_proto_goTypes = []any{
	(AudioEncoding)(0),                   // 0: nvidia.riva.asr.AudioEncoding
	(*StreamingRecognizeRequest)(nil),    // 1: nvidia.riva.asr.StreamingRecognizeRequest
	(*StreamingRecognitionConfig)(nil),   // 2: nvidia.riva.asr.StreamingRecognitionConfig
	(*RecognitionConfig)(nil),            // 3: nvidia.riva.asr.RecognitionConfig
	(*EndpointingConfig)(nil),            // 4: nvidia.riva.asr.EndpointingConfig
	(*StreamingRecognizeResponse)(nil),   // 5: nvidia.riva.asr.StreamingRecognizeResponse
	(*StreamingRecognitionResult)(nil),   // 6: nvidia.riva.asr.StreamingRecognitionResult
	(*SpeechRecognitionAlternative)(nil), // 7: nvidia.riva.asr.SpeechRecognitionAlternative
	nil,                                  // 8: nvidia.riva.asr.RecognitionConfig.CustomConfigurationEntry
}
var file_riva_proto_depIdxs = []int32{
	2, // 0: nvidia.riva.asr.StreamingRecognizeRequest.streaming_config:type_name -> nvidia.riva.asr.StreamingRecognitionConfig
	3, // 1: nvidia.riva.asr.StreamingRecognitionConfig.config:type_name -> nvidia.riva.asr.RecognitionConfig
	0, // 2: nvidia.riva.asr.RecognitionConfig.encoding:type_name -> nvidia.riva.asr.AudioEncoding
	8, // 3: nvidia.riva.asr.RecognitionConfig.custom_configuration:type_name -> nvidia.riva.asr.RecognitionConfig.CustomConfigurationEntry
	4, // 4: nvidia.riva.asr.RecognitionConfig.endpointing_config:type_name -> nvidia.riva.asr.EndpointingConfig
	6, // 5: nvidia.riva.asr.StreamingRecognizeResponse.results:type_name -> nvidia.riva.asr.StreamingRecognitionResult
	7, // 6: nvidia.riva.asr.StreamingRecognitionResult.alternatives:type_name -> nvidia.riva.asr.SpeechRecognitionAlternative
	1, // 7: nvidia.riva.asr.RivaSpeechRecognition.StreamingRecognize:input_type -> nvidia.riva.asr.StreamingRecognizeRequest
	5, // 8: nvidia.riva.asr.RivaSpeechRecognition.StreamingRecognize:output_type -> nvidia.riva.asr.StreamingRecognizeResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_riva_proto_init() }
func file_riva_proto_init() {
	if File_riva_proto != nil {
		return
	}
	file_riva_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamingRecognizeRequest_StreamingConfig)(nil),
		(*StreamingRecognizeRequest_AudioContent)(nil),
	}
	file_riva_proto_msgTypes[2].OneofWrappers = []any{}
	file_riva_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_riva_proto_rawDesc), len(file_riva_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_riva_proto_goTypes,
		DependencyIndexes: file_riva_proto_depIdxs,
		EnumInfos:         file_riva_proto_enumTypes,
		MessageInfos:      file_riva_proto_msgTypes,
	}.Build()
	File_riva_proto = out.File
	file_riva_proto_goTypes = nil
	file_riva_proto_depIdxs = nil
}
