// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: riva.proto

// Minimal subset of the NVIDIA Riva speech-recognition gRPC contract, limited to
// the messages the streaming ASR client uses. Field numbers, the package name,
// and the service/method names match the upstream Riva schema exactly so the
// wire format and the gRPC method path are compatible with any Riva/NIM server
// (hosted NVCF or a locally deployed model such as parakeet). Regenerate with:
//
//	go generate ./provider/nvidia/internal/rivapb

package rivapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RivaSpeechRecognition_StreamingRecognize_FullMethodName = "/nvidia.riva.asr.RivaSpeechRecognition/StreamingRecognize"
)

// RivaSpeechRecognitionClient is the client API for RivaSpeechRecognition service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RivaSpeechRecognition is the Riva ASR service. Only the streaming RPC is
// declared here; batch Recognize and the config RPC are omitted.
type RivaSpeechRecognitionClient interface {
	// StreamingRecognize streams audio to the server and receives interim and
	// final transcripts. The first request on the stream must carry a
	// StreamingRecognitionConfig; every later request carries audio_content.
	StreamingRecognize(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamingRecognizeRequest, StreamingRecognizeResponse], error)
}

type rivaSpeechRecognitionClient struct {
	cc grpc.ClientConnInterface
}

func NewRivaSpeechRecognitionClient(cc grpc.ClientConnInterface) RivaSpeechRecognitionClient {
	return &rivaSpeechRecognitionClient{cc}
}

func (c *rivaSpeechRecognitionClient) StreamingRecognize(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamingRecognizeRequest, StreamingRecognizeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RivaSpeechRecognition_ServiceDesc.Streams[0], RivaSpeechRecognition_StreamingRecognize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamingRecognizeRequest, StreamingRecognizeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RivaSpeechRecognition_StreamingRecognizeClient = grpc.BidiStreamingClient[StreamingRecognizeRequest, StreamingRecognizeResponse]

// RivaSpeechRecognitionServer is the server API for RivaSpeechRecognition service.
// All implementations must embed UnimplementedRivaSpeechRecognitionServer
// for forward compatibility.
//
// RivaSpeechRecognition is the Riva ASR service. Only the streaming RPC is
// declared here; batch Recognize and the config RPC are omitted.
type RivaSpeechRecognitionServer interface {
	// StreamingRecognize streams audio to the server and receives interim and
	// final transcripts. The first request on the stream must carry a
	// StreamingRecognitionConfig; every later request carries audio_content.
	StreamingRecognize(grpc.BidiStreamingServer[StreamingRecognizeRequest, StreamingRecognizeResponse]) error
	mustEmbedUnimplementedRivaSpeechRecognitionServer()
}

// UnimplementedRivaSpeechRecognitionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRivaSpeechRecognitionServer struct{}

func (UnimplementedRivaSpeechRecognitionServer) StreamingRecognize(grpc.BidiStreamingServer[StreamingRecognizeRequest, StreamingRecognizeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamingRecognize not implemented")
}
func (UnimplementedRivaSpeechRecognitionServer) mustEmbedUnimplementedRivaSpeechRecognitionServer() {}
func (UnimplementedRivaSpeechRecognitionServer) testEmbeddedByValue()                               {}

// UnsafeRivaSpeechRecognitionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RivaSpeechRecognitionServer will
// result in compilation errors.
type UnsafeRivaSpeechRecognitionServer interface {
	mustEmbedUnimplementedRivaSpeechRecognitionServer()
}

func RegisterRivaSpeechRecognitionServer(s grpc.ServiceRegistrar, srv RivaSpeechRecognitionServer) {
	// If the following call pancis, it indicates UnimplementedRivaSpeechRecognitionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RivaSpeechRecognition_ServiceDesc, srv)
}

func _RivaSpeechRecognition_StreamingRecognize_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RivaSpeechRecognitionServer).StreamingRecognize(&grpc.GenericServerStream[StreamingRecognizeRequest, StreamingRecognizeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RivaSpeechRecognition_StreamingRecognizeServer = grpc.BidiStreamingServer[StreamingRecognizeRequest, StreamingRecognizeResponse]

// RivaSpeechRecognition_ServiceDesc is the grpc.ServiceDesc for RivaSpeechRecognition service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RivaSpeechRecognition_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nvidia.riva.asr.RivaSpeechRecognition",
	HandlerType: (*RivaSpeechRecognitionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingRecognize",
			Handler:       _RivaSpeechRecognition_StreamingRecognize_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "riva.proto",
}
