// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: riva_tts.proto

// Minimal subset of the NVIDIA Riva speech-synthesis gRPC contract, limited to
// the messages the streaming TTS client uses. Field numbers, the package name,
// and the service/method names match the upstream Riva schema exactly so the
// wire format and the gRPC method path are compatible with any Riva/NIM server
// (hosted NVCF or a locally deployed model such as magpie). Regenerate with:
//
//	go generate ./provider/nvidia/internal/rivapb

package rivapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ZeroShotData carries the audio prompt a zero-shot model clones its voice from.
type ZeroShotData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// audio_prompt is the prompt audio. NVIDIA recommends 3 to 10 seconds.
	AudioPrompt []byte `protobuf:"bytes,1,opt,name=audio_prompt,json=audioPrompt,proto3" json:"audio_prompt,omitempty"`
	// sample_rate_hz is the prompt's rate; the server defaults to 22050.
	SampleRateHz int32 `protobuf:"varint,2,opt,name=sample_rate_hz,json=sampleRateHz,proto3" json:"sample_rate_hz,omitempty"`
	// encoding of the prompt. Only LINEAR_PCM and OGGOPUS are supported.
	Encoding AudioEncoding `protobuf:"varint,3,opt,name=encoding,proto3,enum=nvidia.riva.AudioEncoding" json:"encoding,omitempty"`
	// quality is how many times the prompt is passed through the decoder, 1 to
	// 40. The server defaults to 20.
	Quality int32 `protobuf:"varint,4,opt,name=quality,proto3" json:"quality,omitempty"`
	// transcript of the prompt audio.
	Transcript    string `protobuf:"bytes,5,opt,name=transcript,proto3" json:"transcript,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZeroShotData) Reset() {
	*x = ZeroShotData{}
	mi := &file_riva_tts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZeroShotData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZeroShotData) ProtoMessage() {}

func (x *ZeroShotData) ProtoReflect() protoreflect.Message {
	mi := &file_riva_tts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZeroShotData.ProtoReflect.Descriptor instead.
func (*ZeroShotData) Descriptor() ([]byte, []int) {
	return file_riva_tts_proto_rawDescGZIP(), []int{0}
}

func (x *ZeroShotData) GetAudioPrompt() []byte {
	if x != nil {
		return x.AudioPrompt
	}
	return nil
}

func (x *ZeroShotData) GetSampleRateHz() int32 {
	if x != nil {
		return x.SampleRateHz
	}
	return 0
}

func (x *ZeroShotData) GetEncoding() AudioEncoding {
	if x != nil {
		return x.Encoding
	}
	return AudioEncoding_ENCODING_UNSPECIFIED
}

func (x *ZeroShotData) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *ZeroShotData) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

// SynthesizeSpeechRequest asks for one span of text to be spoken.
type SynthesizeSpeechRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Text         string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	LanguageCode string                 `protobuf:"bytes,2,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	Encoding     AudioEncoding          `protobuf:"varint,3,opt,name=encoding,proto3,enum=nvidia.riva.AudioEncoding" json:"encoding,omitempty"`
	// sample_rate_hz is the rate the generated audio is resampled to.
	SampleRateHz int32  `protobuf:"varint,4,opt,name=sample_rate_hz,json=sampleRateHz,proto3" json:"sample_rate_hz,omitempty"`
	VoiceName    string `protobuf:"bytes,5,opt,name=voice_name,json=voiceName,proto3" json:"voice_name,omitempty"`
	// zero_shot_data is required by zero-shot models and ignored by the others.
	ZeroShotData *ZeroShotData `protobuf:"bytes,6,opt,name=zero_shot_data,json=zeroShotData,proto3" json:"zero_shot_data,omitempty"`
	// custom_dictionary is comma-separated grapheme/phoneme pairs, each pair
	// separated by two spaces.
	CustomDictionary string `protobuf:"bytes,7,opt,name=custom_dictionary,json=customDictionary,proto3" json:"custom_dictionary,omitempty"`
	// custom_configuration carries model-specific options the schema does not
	// name, for example "exaggeration_factor".
	CustomConfiguration map[string]string `protobuf:"bytes,8,rep,name=custom_configuration,json=customConfiguration,proto3" json:"custom_configuration,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SynthesizeSpeechRequest) Reset() {
	*x = SynthesizeSpeechRequest{}
	mi := &file_riva_tts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeSpeechRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeSpeechRequest) ProtoMessage() {}

func (x *SynthesizeSpeechRequest) ProtoReflect() protoreflect.Message {
	mi := &file_riva_tts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeSpeechRequest.ProtoReflect.Descriptor instead.
func (*SynthesizeSpeechRequest) Descriptor() ([]byte, []int) {
	return file_riva_tts_proto_rawDescGZIP(), []int{1}
}

func (x *SynthesizeSpeechRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeSpeechRequest) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *SynthesizeSpeechRequest) GetEncoding() AudioEncoding {
	if x != nil {
		return x.Encoding
	}
	return AudioEncoding_ENCODING_UNSPECIFIED
}

func (x *SynthesizeSpeechRequest) GetSampleRateHz() int32 {
	if x != nil {
		return x.SampleRateHz
	}
	return 0
}

func (x *SynthesizeSpeechRequest) GetVoiceName() string {
	if x != nil {
		return x.VoiceName
	}
	return ""
}

func (x *SynthesizeSpeechRequest) GetZeroShotData() *ZeroShotData {
	if x != nil {
		return x.ZeroShotData
	}
	return nil
}

func (x *SynthesizeSpeechRequest) GetCustomDictionary() string {
	if x != nil {
		return x.CustomDictionary
	}
	return ""
}

func (x *SynthesizeSpeechRequest) GetCustomConfiguration() map[string]string {
	if x != nil {
		return x.CustomConfiguration
	}
	return nil
}

// SynthesizeSpeechResponseMetadata reports the text the server actually spoke.
// Upstream marks it experimental and subject to change.
type SynthesizeSpeechResponseMetadata struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Text               string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	ProcessedText      string                 `protobuf:"bytes,2,opt,name=processed_text,json=processedText,proto3" json:"processed_text,omitempty"`
	PredictedDurations []float32              `protobuf:"fixed32,8,rep,packed,name=predicted_durations,json=predictedDurations,proto3" json:"predicted_durations,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SynthesizeSpeechResponseMetadata) Reset() {
	*x = SynthesizeSpeechResponseMetadata{}
	mi := &file_riva_tts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeSpeechResponseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeSpeechResponseMetadata) ProtoMessage() {}

func (x *SynthesizeSpeechResponseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_riva_tts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeSpeechResponseMetadata.ProtoReflect.Descriptor instead.
func (*SynthesizeSpeechResponseMetadata) Descriptor() ([]byte, []int) {
	return file_riva_tts_proto_rawDescGZIP(), []int{2}
}

func (x *SynthesizeSpeechResponseMetadata) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeSpeechResponseMetadata) GetProcessedText() string {
	if x != nil {
		return x.ProcessedText
	}
	return ""
}

func (x *SynthesizeSpeechResponseMetadata) GetPredictedDurations() []float32 {
	if x != nil {
		return x.PredictedDurations
	}
	return nil
}

// SynthesizeSpeechResponse is one chunk of generated audio.
type SynthesizeSpeechResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Audio         []byte                            `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	Meta          *SynthesizeSpeechResponseMetadata `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeSpeechResponse) Reset() {
	*x = SynthesizeSpeechResponse{}
	mi := &file_riva_tts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeSpeechResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeSpeechResponse) ProtoMessage() {}

func (x *SynthesizeSpeechResponse) ProtoReflect() protoreflect.Message {
	mi := &file_riva_tts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeSpeechResponse.ProtoReflect.Descriptor instead.
func (*SynthesizeSpeechResponse) Descriptor() ([]byte, []int) {
	return file_riva_tts_proto_rawDescGZIP(), []int{3}
}

func (x *SynthesizeSpeechResponse) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *SynthesizeSpeechResponse) GetMeta() *SynthesizeSpeechResponseMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_riva_tts_proto protoreflect.FileDescriptor

const file_riva_tts_proto_rawDesc = "" +
	"\n" +
	"\x0eriva_tts.proto\x12\x0fnvidia.riva.tts\x1a\x10riva_audio.proto\"\xc9\x01\n" +
	"\fZeroShotData\x12!\n" +
	"\faudio_prompt\x18\x01 \x01(\fR\vaudioPrompt\x12$\n" +
	"\x0esample_rate_hz\x18\x02 \x01(\x05R\fsampleRateHz\x126\n" +
	"\bencoding\x18\x03 \x01(\x0e2\x1a.nvidia.riva.AudioEncodingR\bencoding\x12\x18\n" +
	"\aquality\x18\x04 \x01(\x05R\aquality\x12\x1e\n" +
	"\n" +
	"transcript\x18\x05 \x01(\tR\n" +
	"transcript\"\xff\x03\n" +
	"\x17SynthesizeSpeechRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12#\n" +
	"\rlanguage_code\x18\x02 \x01(\tR\flanguageCode\x126\n" +
	"\bencoding\x18\x03 \x01(\x0e2\x1a.nvidia.riva.AudioEncodingR\bencoding\x12$\n" +
	"\x0esample_rate_hz\x18\x04 \x01(\x05R\fsampleRateHz\x12\x1d\n" +
	"\n" +
	"voice_name\x18\x05 \x01(\tR\tvoiceName\x12C\n" +
	"\x0ezero_shot_data\x18\x06 \x01(\v2\x1d.nvidia.riva.tts.ZeroShotDataR\fzeroShotData\x12+\n" +
	"\x11custom_dictionary\x18\a \x01(\tR\x10customDictionary\x12t\n" +
	"\x14custom_configuration\x18\b \x03(\v2A.nvidia.riva.tts.SynthesizeSpeechRequest.CustomConfigurationEntryR\x13customConfiguration\x1aF\n" +
	"\x18CustomConfigurationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	" SynthesizeSpeechResponseMetadata\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12%\n" +
	"\x0eprocessed_text\x18\x02 \x01(\tR\rprocessedText\x12/\n" +
	"\x13predicted_durations\x18\b \x03(\x02R\x12predictedDurations\"w\n" +
	"\x18SynthesizeSpeechResponse\x12\x14\n" +
	"\x05audio\x18\x01 \x01(\fR\x05audio\x12E\n" +
	"\x04meta\x18\x02 \x01(\v21.nvidia.riva.tts.SynthesizeSpeechResponseMetadataR\x04meta2\x84\x01\n" +
	"\x13RivaSpeechSynthesis\x12m\n" +
	"\x10SynthesizeOnline\x12(.nvidia.riva.tts.SynthesizeSpeechRequest\x1a).nvidia.riva.tts.SynthesizeSpeechResponse\"\x00(\x010\x01BAZ?github.com/gojargo/jargo/provider/nvidia/internal/rivapb;rivapbb\x06proto3"

var (
	file_riva_tts_proto_rawDescOnce sync.Once
	file_riva_tts_proto_rawDescData []byte
)

func file_riva_tts_proto_rawDescGZIP() []byte {
	file_riva_tts_proto_rawDescOnce.Do(func() {
		file_riva_tts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_riva_tts_proto_rawDesc), len(file_riva_tts_proto_rawDesc)))
	})
	return file_riva_tts_proto_rawDescData
}

var file_riva_tts_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_riva_tts_proto_goTypes = []any{
	(*ZeroShotData)(nil),                     // 0: nvidia.riva.tts.ZeroShotData
	(*SynthesizeSpeechRequest)(nil),          // 1: nvidia.riva.tts.SynthesizeSpeechRequest
	(*SynthesizeSpeechResponseMetadata)(nil), // 2: nvidia.riva.tts.SynthesizeSpeechResponseMetadata
	(*SynthesizeSpeechResponse)(nil),         // 3: nvidia.riva.tts.SynthesizeSpeechResponse
	nil,                                      // 4: nvidia.riva.tts.SynthesizeSpeechRequest.CustomConfigurationEntry
	(AudioEncoding)(0),                       // 5: nvidia.riva.AudioEncoding
}
var file_riva_tts_proto_depIdxs = []int32{
	5, // 0: nvidia.riva.tts.ZeroShotData.encoding:type_name -> nvidia.riva.AudioEncoding
	5, // 1: nvidia.riva.tts.SynthesizeSpeechRequest.encoding:type_name -> nvidia.riva.AudioEncoding
	0, // 2: nvidia.riva.tts.SynthesizeSpeechRequest.zero_shot_data:type_name -> nvidia.riva.tts.ZeroShotData
	4, // 3: nvidia.riva.tts.SynthesizeSpeechRequest.custom_configuration:type_name -> nvidia.riva.tts.SynthesizeSpeechRequest.CustomConfigurationEntry
	2, // 4: nvidia.riva.tts.SynthesizeSpeechResponse.meta:type_name -> nvidia.riva.tts.SynthesizeSpeechResponseMetadata
	1, // 5: nvidia.riva.tts.RivaSpeechSynthesis.SynthesizeOnline:input_type -> nvidia.riva.tts.SynthesizeSpeechRequest
	3, // 6: nvidia.riva.tts.RivaSpeechSynthesis.SynthesizeOnline:output_type -> nvidia.riva.tts.SynthesizeSpeechResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_riva_tts_proto_init() }
func file_riva_tts_proto_init() {
	if File_riva_tts_proto != nil {
		return
	}
	file_riva_audio_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_riva_tts_proto_rawDesc), len(file_riva_tts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_riva_tts_proto_goTypes,
		DependencyIndexes: file_riva_tts_proto_depIdxs,
		MessageInfos:      file_riva_tts_proto_msgTypes,
	}.Build()
	File_riva_tts_proto = out.File
	file_riva_tts_proto_goTypes = nil
	file_riva_tts_proto_depIdxs = nil
}
