package frames

import "fmt"

// AudioRawData is the raw-audio payload shared by the audio frame types. It
// carries a chunk of PCM audio plus the metadata needed to interpret it; the
// audio frames embed it alongside a category base.
type AudioRawData struct {
	// Audio is raw PCM audio: 16-bit signed samples, interleaved by channel.
	Audio []byte
	// SampleRate is the audio sample rate in Hz.
	SampleRate int
	// NumChannels is the number of interleaved audio channels.
	NumChannels int
}

// newAudioRawData builds an AudioRawData from PCM audio.
func newAudioRawData(audio []byte, sampleRate, numChannels int) AudioRawData {
	return AudioRawData{Audio: audio, SampleRate: sampleRate, NumChannels: numChannels}
}

// AudioData returns the raw-audio payload itself, so a frame carrying audio can
// be handled through the AudioFrame interface without knowing which kind it is.
func (a *AudioRawData) AudioData() *AudioRawData { return a }

// AudioFrame is implemented by every frame that carries raw audio, whichever
// direction it travels in.
type AudioFrame interface {
	Frame
	AudioData() *AudioRawData
}

// OutputAudioFrame is implemented by every frame carrying audio bound for an
// output transport: plain output audio, TTS audio, and speech-stream audio. A
// transport takes one rather than a bare buffer, so it can read the destination
// the frame names alongside the samples and send it on the right outgoing
// stream. Assert this interface rather than a concrete type, so audio keeps
// being handled whichever kind produced it.
type OutputAudioFrame interface {
	AudioFrame
	isOutputAudio()
}

// NumFrames is the number of audio frames (samples per channel) in the buffer:
// len(Audio) / (NumChannels * 2) for 16-bit PCM. It is 0 when NumChannels is
// unset. It is derived on each call, so it stays correct when Audio is replaced.
func (a *AudioRawData) NumFrames() int {
	if a.NumChannels <= 0 {
		return 0
	}
	return len(a.Audio) / (a.NumChannels * 2)
}

// InputAudioRawFrame is a chunk of audio coming from an input transport. When a
// transport exposes multiple audio sources, the source name is carried in
// TransportSource. It is a system frame.
type InputAudioRawFrame struct {
	BaseSystemFrame
	AudioRawData
}

// NewInputAudioRawFrame builds an InputAudioRawFrame from PCM audio.
func NewInputAudioRawFrame(audio []byte, sampleRate, numChannels int) *InputAudioRawFrame {
	return &InputAudioRawFrame{
		BaseSystemFrame: NewBaseSystemFrame("InputAudioRawFrame"),
		AudioRawData:    newAudioRawData(audio, sampleRate, numChannels),
	}
}

// String implements fmt.Stringer.
func (f *InputAudioRawFrame) String() string {
	return fmt.Sprintf("%s(pts: %s, source: %s, size: %d, frames: %d, sample_rate: %d, channels: %d)",
		f.Name(), formatPTS(f), f.TransportSource(), len(f.Audio), f.NumFrames(), f.SampleRate, f.NumChannels)
}

// OutputAudioRawFrame is a chunk of audio to be played by an output transport.
// When a transport exposes multiple audio destinations, the destination name is
// carried in TransportDestination. It is a data frame.
type OutputAudioRawFrame struct {
	BaseDataFrame
	AudioRawData
}

// isOutputAudio marks this frame and the ones embedding it as output audio.
func (*OutputAudioRawFrame) isOutputAudio() {}

// NewOutputAudioRawFrame builds an OutputAudioRawFrame from PCM audio.
func NewOutputAudioRawFrame(audio []byte, sampleRate, numChannels int) *OutputAudioRawFrame {
	return &OutputAudioRawFrame{
		BaseDataFrame: NewBaseDataFrame("OutputAudioRawFrame"),
		AudioRawData:  newAudioRawData(audio, sampleRate, numChannels),
	}
}

// String implements fmt.Stringer.
func (f *OutputAudioRawFrame) String() string {
	return fmt.Sprintf("%s(pts: %s, destination: %s, size: %d, frames: %d, sample_rate: %d, channels: %d)",
		f.Name(), formatPTS(f), f.TransportDestination(), len(f.Audio), f.NumFrames(), f.SampleRate, f.NumChannels)
}

// TTSAudioRawFrame is a chunk of output audio generated by a TTS service, ready
// for playback.
type TTSAudioRawFrame struct {
	OutputAudioRawFrame
	// ContextID identifies the TTS context that generated this audio; "" when
	// unset.
	ContextID string
}

// NewTTSAudioRawFrame builds a TTSAudioRawFrame from PCM audio.
func NewTTSAudioRawFrame(audio []byte, sampleRate, numChannels int) *TTSAudioRawFrame {
	return &TTSAudioRawFrame{
		OutputAudioRawFrame: OutputAudioRawFrame{
			BaseDataFrame: NewBaseDataFrame("TTSAudioRawFrame"),
			AudioRawData:  newAudioRawData(audio, sampleRate, numChannels),
		},
	}
}

// SpeechOutputAudioRawFrame is one chunk of a continuous stream of speech audio.
// The stream can also carry silence between utterances, so a consumer that needs
// to tell the two apart has to test the samples themselves.
type SpeechOutputAudioRawFrame struct {
	OutputAudioRawFrame
}

// NewSpeechOutputAudioRawFrame builds a SpeechOutputAudioRawFrame from PCM audio.
func NewSpeechOutputAudioRawFrame(audio []byte, sampleRate, numChannels int) *SpeechOutputAudioRawFrame {
	return &SpeechOutputAudioRawFrame{
		OutputAudioRawFrame: OutputAudioRawFrame{
			BaseDataFrame: NewBaseDataFrame("SpeechOutputAudioRawFrame"),
			AudioRawData:  newAudioRawData(audio, sampleRate, numChannels),
		},
	}
}

// Compile-time interface checks.
var (
	_ SystemFrame = (*InputAudioRawFrame)(nil)
	_ DataFrame   = (*OutputAudioRawFrame)(nil)
	_ DataFrame   = (*TTSAudioRawFrame)(nil)
	_ DataFrame   = (*SpeechOutputAudioRawFrame)(nil)
)
