package frames

import "fmt"

// AudioRawData is the raw-audio payload shared by the audio frame types. It
// carries a chunk of PCM audio plus the metadata needed to interpret it; the
// audio frames embed it alongside a category base.
type AudioRawData struct {
	// Audio is raw PCM audio: 16-bit signed samples, interleaved by channel.
	Audio []byte
	// SampleRate is the audio sample rate in Hz.
	SampleRate int
	// NumChannels is the number of interleaved audio channels.
	NumChannels int

	numFrames int
}

// newAudioRawData builds an AudioRawData and derives its frame count from the
// buffer length.
func newAudioRawData(audio []byte, sampleRate, numChannels int) AudioRawData {
	d := AudioRawData{Audio: audio, SampleRate: sampleRate, NumChannels: numChannels}
	d.recountFrames()
	return d
}

// NumFrames is the number of audio frames (samples per channel) in the buffer:
// len(Audio) / (NumChannels * 2) for 16-bit PCM. It is 0 when NumChannels is
// unset.
func (a *AudioRawData) NumFrames() int { return a.numFrames }

func (a *AudioRawData) recountFrames() {
	if a.NumChannels > 0 {
		a.numFrames = len(a.Audio) / (a.NumChannels * 2)
	}
}

// InputAudioRawFrame is a chunk of audio coming from an input transport. When a
// transport exposes multiple audio sources, the source name is carried in
// TransportSource. It is a system frame.
type InputAudioRawFrame struct {
	BaseSystemFrame
	AudioRawData
}

// NewInputAudioRawFrame builds an InputAudioRawFrame from PCM audio.
func NewInputAudioRawFrame(audio []byte, sampleRate, numChannels int) *InputAudioRawFrame {
	return &InputAudioRawFrame{
		BaseSystemFrame: NewBaseSystemFrame("InputAudioRawFrame"),
		AudioRawData:    newAudioRawData(audio, sampleRate, numChannels),
	}
}

// String implements fmt.Stringer.
func (f *InputAudioRawFrame) String() string {
	return fmt.Sprintf("%s(pts: %s, source: %s, size: %d, frames: %d, sample_rate: %d, channels: %d)",
		f.Name(), formatPTS(f), f.TransportSource(), len(f.Audio), f.NumFrames(), f.SampleRate, f.NumChannels)
}

// OutputAudioRawFrame is a chunk of audio to be played by an output transport.
// When a transport exposes multiple audio destinations, the destination name is
// carried in TransportDestination. It is a data frame.
type OutputAudioRawFrame struct {
	BaseDataFrame
	AudioRawData
}

// NewOutputAudioRawFrame builds an OutputAudioRawFrame from PCM audio.
func NewOutputAudioRawFrame(audio []byte, sampleRate, numChannels int) *OutputAudioRawFrame {
	return &OutputAudioRawFrame{
		BaseDataFrame: NewBaseDataFrame("OutputAudioRawFrame"),
		AudioRawData:  newAudioRawData(audio, sampleRate, numChannels),
	}
}

// String implements fmt.Stringer.
func (f *OutputAudioRawFrame) String() string {
	return fmt.Sprintf("%s(pts: %s, destination: %s, size: %d, frames: %d, sample_rate: %d, channels: %d)",
		f.Name(), formatPTS(f), f.TransportDestination(), len(f.Audio), f.NumFrames(), f.SampleRate, f.NumChannels)
}

// TTSAudioRawFrame is a chunk of output audio generated by a TTS service, ready
// for playback.
type TTSAudioRawFrame struct {
	OutputAudioRawFrame
	// ContextID identifies the TTS context that generated this audio; "" when
	// unset.
	ContextID string
}

// NewTTSAudioRawFrame builds a TTSAudioRawFrame from PCM audio.
func NewTTSAudioRawFrame(audio []byte, sampleRate, numChannels int) *TTSAudioRawFrame {
	return &TTSAudioRawFrame{
		OutputAudioRawFrame: OutputAudioRawFrame{
			BaseDataFrame: NewBaseDataFrame("TTSAudioRawFrame"),
			AudioRawData:  newAudioRawData(audio, sampleRate, numChannels),
		},
	}
}

// Compile-time interface checks.
var (
	_ SystemFrame = (*InputAudioRawFrame)(nil)
	_ DataFrame   = (*OutputAudioRawFrame)(nil)
	_ DataFrame   = (*TTSAudioRawFrame)(nil)
)
